language: haxe

sudo: required
dist: trusty

os:
  - linux
  - osx

haxe:
  - "3.2.1"
  - development

branches:
  only:
    - develop

matrix:
  allow_failures:
    - haxe: development
    - os: osx

install:
  - haxelib install hxlog
  - haxelib dev hxmake .
  - haxe build.hxml

script:
  - haxelib run hxmake _
  - hxmake _
  - hxmake haxe
